import{S,i as f,a as w}from"./assets/vendor-1feca4b1.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function l(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=l(e);fetch(e.href,r)}})();const c=document.querySelector(".form"),$=document.querySelector(".input");document.querySelector(".btn");const d=document.querySelector(".load-btn"),h=document.querySelector(".gallery"),m=document.querySelector(".spinner"),y=new S(".gallery a"),E="41458722-788aa599ff2a579d31eb49587";let g,n,p,b;const P=40,o=new URL("https://pixabay.com/api/");o.searchParams.append("key",`${E}`);o.searchParams.append("image_type","photo");o.searchParams.append("orientation","horizontal");o.searchParams.append("safesearch","true");o.searchParams.append("per_page",P);$.addEventListener("input",a=>{g=a.target.value});const v=async()=>(o.searchParams.delete("q"),o.searchParams.append("q",g),o.searchParams.delete("page"),o.searchParams.append("page",n),(await w.get(o)).data);c.addEventListener("submit",a=>{a.preventDefault(),m.classList.add("loader"),n=1,h.innerHTML="",v().then(t=>{t.total===0&&u(),p=t.totalHits,b=Math.ceil(p/P),L(t.hits),y.refresh(),d.style.display="block"}).catch(t=>{u()}).finally(()=>{c.reset(),m.classList.remove("loader")})});d.addEventListener("click",a=>{a.preventDefault(),n+=1,v().then(t=>{n>=b&&(d.style.display="none",f.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),L(t.hits),y.refresh(),window.scrollBy({top:540,behavior:"smooth"})}).catch(t=>{u()}).finally(()=>{c.reset(),m.classList.remove("loader")})});function L(a){h.insertAdjacentHTML("beforeend",a.reduce((t,{largeImageURL:l,webformatURL:i,likes:e,views:r,comments:s,downloads:q})=>t+`<li class="gallery-item">
          <a href="${l}">
            <div class="pic-item">
              <img src="${i}" alt="photo">
            </div>
            <ul class="information-list">
              <li class="information-item">likes<br>${e}</li>
              <li class="information-item">views<br>${r}</li>
              <li class="information-item">comments<br>${s}</li>
              <li class="information-item">downloads<br>${q}</li>
            </ul>
          </a>
        </li>`,""))}function u(){f.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}
//# sourceMappingURL=commonHelpers.js.map
