import{S as w,i as u,a as S}from"./assets/vendor-1feca4b1.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function c(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerpolicy&&(a.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?a.credentials="include":e.crossorigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function l(e){if(e.ep)return;e.ep=!0;const a=c(e);fetch(e.href,a)}})();const d=document.querySelector(".form"),$=document.querySelector(".input");document.querySelector(".btn");const n=document.querySelector(".load-btn"),y=document.querySelector(".gallery"),m=document.querySelector(".spinner"),g=new w(".gallery a"),E="41458722-788aa599ff2a579d31eb49587";let h,s,f,p;const P=40,r=new URL("https://pixabay.com/api/");r.searchParams.append("key",`${E}`);r.searchParams.append("image_type","photo");r.searchParams.append("orientation","horizontal");r.searchParams.append("safesearch","true");r.searchParams.append("per_page",P);$.addEventListener("input",o=>{h=o.target.value});const b=async()=>(await S.get(r)).data;d.addEventListener("submit",o=>{o.preventDefault(),m.classList.add("loader"),s=1,y.innerHTML="",r.searchParams.delete("q"),r.searchParams.append("q",h),r.searchParams.delete("page"),r.searchParams.append("page",s),b().then(t=>{t.total===0&&(n.style.display="none",iziError()),f=t.totalHits,p=Math.ceil(f/P),v(t.hits),t.total!==0&&(n.style.display="block"),g.refresh(),s>=p&&(n.style.display="none",u.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}).catch(t=>{L()}).finally(()=>{d.reset(),m.classList.remove("loader")})});n.addEventListener("click",o=>{o.preventDefault(),s+=1,r.searchParams.delete("q"),r.searchParams.append("q",h),r.searchParams.delete("page"),r.searchParams.append("page",s),b().then(t=>{s>=p&&(n.style.display="none",u.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),v(t.hits),g.refresh(),window.scrollBy({top:540,behavior:"smooth"})}).catch(t=>{L()}).finally(()=>{d.reset(),m.classList.remove("loader")})});function v(o){y.insertAdjacentHTML("beforeend",o.reduce((t,{largeImageURL:c,webformatURL:l,likes:e,views:a,comments:i,downloads:q})=>t+`<li class="gallery-item">
          <a href="${c}">
            <div class="pic-item">
              <img src="${l}" alt="photo">
            </div>
            <ul class="information-list">
              <li class="information-item">likes<br>${e}</li>
              <li class="information-item">views<br>${a}</li>
              <li class="information-item">comments<br>${i}</li>
              <li class="information-item">downloads<br>${q}</li>
            </ul>
          </a>
        </li>`,""))}function L(){u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}
//# sourceMappingURL=commonHelpers.js.map
